"""
AUTO-APPLY — browser-use wrapper for ABHIMANYU 2.0
Submits applications on T480/T440p via browser automation.
Falls back to manual-submit blueprint generation on phone.

Usage:
  python scripts/auto_apply.py --company CompanyName --resume path/to/resume.docx
  python scripts/auto_apply.py --company CompanyName --manual  (phone fallback)

Requires: pip install browser-use playwright
"""

import argparse
import json
import os
import sys
from pathlib import Path

def generate_manual_blueprint(company, resume_path, cover_letter_path=None):
    """Generate field-by-field submission blueprint for phone manual submission."""
    blueprint = f"""# MANUAL SUBMIT BLUEPRINT — {company}
# Generated by AUTO-APPLY (phone fallback mode)

## URL
Open careers page for {company} in your phone browser.

## Field Mappings
1. Full Name: [NAME]
2. Email: [EMAIL]
3. Phone: [PHONE]
4. Resume: Upload {resume_path}
"""
    if cover_letter_path:
        blueprint += f"5. Cover Letter: Upload {cover_letter_path}\n"

    blueprint += """
## Step-by-Step
1. Open company's careers page
2. Search for the target role
3. Click Apply
4. Fill each field from the mapping above
5. Upload resume document
6. Review and submit
7. Say SUBMITTED when done

## Files to Upload
"""
    blueprint += f"- Resume: {resume_path}\n"
    if cover_letter_path:
        blueprint += f"- Cover Letter: {cover_letter_path}\n"

    return blueprint


def auto_apply_browser(company, resume_path, cover_letter_path=None):
    """Use browser-use to auto-fill and submit application."""
    try:
        from browser_use import Agent
        from langchain_openai import ChatOpenAI
    except ImportError:
        print("ERROR: browser-use not installed. Run: pip install browser-use")
        print("Falling back to manual blueprint...")
        return generate_manual_blueprint(company, resume_path, cover_letter_path)

    task = f"""
    Go to {company}'s careers page. Find the operations/strategy role we selected.
    Click Apply. Fill in my details:
    - Name: [NAME]
    - Email: [EMAIL]
    - Phone: [PHONE]
    Upload resume from {resume_path}.
    """

    if cover_letter_path:
        task += f" Upload cover letter from {cover_letter_path}.\n"

    task += "Submit the application. Confirm submission was successful."

    try:
        agent = Agent(
            task=task,
            llm=ChatOpenAI(model="gpt-4o"),
        )
        result = agent.run()
        return f"✅ AUTO-APPLY completed for {company}\nResult: {result}"
    except Exception as e:
        return f"⚠️ AUTO-APPLY failed: {e}\nFalling back to manual blueprint.\n" + \
               generate_manual_blueprint(company, resume_path, cover_letter_path)


def main():
    parser = argparse.ArgumentParser(description='AUTO-APPLY for ABHIMANYU 2.0')
    parser.add_argument('--company', required=True, help='Target company name')
    parser.add_argument('--resume', default=None, help='Path to resume DOCX')
    parser.add_argument('--cover-letter', default=None, help='Path to cover letter DOCX')
    parser.add_argument('--manual', action='store_true', help='Force manual blueprint mode')

    args = parser.parse_args()

    # Check if browser-use is available
    has_browser_use = False
    try:
        import browser_use
        has_browser_use = True
    except ImportError:
        pass

    if args.manual or not has_browser_use:
        print(generate_manual_blueprint(args.company, args.resume, args.cover_letter))
    else:
        result = auto_apply_browser(args.company, args.resume, args.cover_letter)
        print(result)


if __name__ == '__main__':
    main()
